Demohack2022/hacktoberfest2022

electronic_shop.java
proj.c

java code for an electronic shop to perform basic functionalities of the electronic shops like inventory management, billing, earning and record of purchases

Electronic Shop inventory and management system using java

---

Snake Game

Created Snake Game Main

---

atm.c

Simple Static ATM Code using C Program

Simple ATM Code

---

Dark Knight.py

It Makes The Graphical Image of Batman Symbol.
//needs turtle to run

Bat Symbol Graphic Using Python

---

loginsystem/forgetpass.php
loginsystem/login.php
loginsystem/loginid.sql
loginsystem/logout.php
loginsystem/signup.php
loginsystem/welcome.php

Login System using php and a database to store Login ID's and passwords and also has options like register, login, forget password and also welcome page after login creates a session and all

LOGIN System Using php and DB

---

simple_interest.c

simple_interest.c

---

blog/blog.html
blog/design.css
blog/java.js

blog page you can add edit and delete blogs on this webpage

Blog Page using HTML, CSS and JS

---

Minesweeper.cpp.cpp

MineSweeper using C++

---

SETrelations.c
fact.py
rockPaperScissor.java

Added the iterative way of finding the factorial. Time complexity : O(n).

Added another method to find factorial

---

change color.html

This program will change the Text color on clicking the button.

Change Text Color on Button Click

---

product_website.html

Created a simple  product website using HTML and CSS only.

product_website.html

---

login_pg.html

Basic Login page to any social media account.

login_pg.html

---

ipValidator.html

Ip address validation with HTML and Javascript. Basic Regex logic used to check if the given IP address is in valid format or not.

Added Ip address validator

---

Ripple Button Effect/index.html
Ripple Button Effect/style.css

Ripple Button Effect is a cool glowing button effect, whenever the button is clicked and the glow effect on the button is dynamically spread in all areas of the button

Added New Project (Ripple Button)

---

Quiz Project/Client.java

Creating Quiz Project in java, adding Client.java file in it. Please consider this PR

Create Client.java file in Quiz Project

---

primeornot.c

It checks whether the entered number is prime or not.

Prime or not

---

calculator.py

Completed an assigned task of creating a simple python calculator

A Simple Python CALCULATOR

---

squarert.py

this is a simple python program to find square root of any number.

squarert.py

---

Reverse_nodes_in_k_groups.cpp

Example 1:
Input: head = [1,2,3,4,5], k = 2
Output: [2,1,4,3,5]
Example 2:
Input: head = [1,2,3,4,5], k = 3
Output: [3,2,1,4,5]

code for reversing nodes in k groups of LL

---

calendar.py

this is a program to display calendar of any month and year.

calendar.py

---

YouTube_Search/main.py

Created YouTube_Search/main.py

---

TASK-Management/Elec_bill.c

Elec_bill.c

---

todolist.html

Added code for to do list

---

currency_converter.py

Currency Converter in Python - Ruchir Upadhyay

Currency Converter

---

BMI/index.html
BMI/main.js
BMI/stylesheet.css

added BMI calculator using js
